name: Database Generation

on:
  push:
    branches:
    - main
    paths:
    - 'x86_64/**'
  pull_request:
    paths:
    - 'x86_64/**'
  workflow_dispatch:

env:
  GITHUB_USERNAME: Dakkshesh
  GITHUB_EMAIL: dakkshesh5@gmail.com
  GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

jobs:
  dbgen:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/neutron-toolchains/docker-image:arch-neutron

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
          gh auth login --with-token <<< $GHUB_TOKEN
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
          sed -i "s/.*COMPRESSZST=.*/COMPRESSZST=(zstd -c -z -q -10 -T0 -)/" /etc/makepkg.conf
          sed -i "s/.*PACKAGER=.*/PACKAGER='Dakkshesh <dakkshesh5@gmail.com>'/" /etc/makepkg.conf
          sed -i "s/.*GPGKEY=.*/GPGKEY='69FE650875EC4CD630C36FA212E5D2B4F137262E'/" /etc/makepkg.conf

      - name: Delete existing database
        run: |
          cd $(pwd)/x86_64
          rm -rf aether.db
          rm -rf aether.db*.sig
          rm -rf aether.db.tar.zst
          rm -rf aether.files
          rm -rf aether.files*.sig
          rm -rf aether.files.tar.zst
          cd ..

      - name: Generate new database
        run: |
          cd $(pwd)/x86_64
          repo-add --verify --sign --key 69FE650875EC4CD630C36FA212E5D2B4F137262E aether.db.tar.zst *.pkg.tar.zst
          rm -rf aether.db
          rm -rf aether.files
          rm -rf aether.files.sig
          rm -rf aether.db.sig
          cp aether.db.tar.zst aether.db
          cp aether.files.tar.zst aether.files
          cp aether.files.tar.zst.sig aether.files.sig
          cp aether.db.tar.zst.sig aether.db.sig
